### ISSUE TITLE
ACTION REQUIRED: Changes to pulling Chainguard Images

### ISSUE THREAD

**Issue by chainguard-alerter** [uwu-tools/gh-jira-issue-sync#152]
Hey there [Chainguard](https://github.com/chainguard-dev) here.

We noticed that you are using [Chainguard Images](https://github.com/chainguard-images/images), thank you! We wanted to make you aware of an upcoming change that will impact your project.

Starting August 16, 2023 public users will no longer be able to pull images from our registry (cgr.dev/chainguard) by tags other than `latest` or `latest-dev`. Please see [the announcement](https://www.chainguard.dev/unchained/scaling-chainguard-images-with-a-growing-catalog-and-proactive-security-updates) for more information.

You are currently using the following.

In https://github.com/uwu-tools/gh-jira-issue-sync/blob/a69ffbf554c08a4bf4ee7d2be6bc6228e4ed8e49/Dockerfile:

- cgr.dev/chainguard/go:1.20

Our goal is to prevent your project from experiencing any disruptions. Please see [the migration guide](https://www.chainguard.dev/unchained/a-guide-on-how-to-use-chainguard-images-for-public-catalog-tier-users) for options.

If there's more we can do to help please reply to this issue or email us at [support@chainguard.dev](mailto:support@chainguard.dev).

Thank you!

**Comment by rappizs** [comment]
@justaugustus what should we do in this case? I wouldn't suggest to use the `latest` tag, should we look for another base image?

**Comment by mattmoor** [comment]
I think your switch to the go:1.20 image was probably a mistake.  That image is the golang toolchain, which is larger than the alpine base it replaces.  Do you actually need go for opening tickets?

I think what you want is: cgr.dev/chainguard/static:latest-glibc

That is intended as a runtime image for go programs and so minimal that there is really little risk in tracking latest.  You could pin digests and use tooling to bump it if you’d like tho.

**Comment by rappizs** [comment]
> I think your switch to the go:1.20 image was probably a mistake.

Indeed, it was. Thanks for the info and the suggestion!

**Comment by amouat** [comment]
I had a look at this and I think a multi-stage build would help you, so I opened PR #154. 

Using a digest avoids the issue with tags described in this issue but the multi-stage build is nice for reducing the image size and attack surface. You could also change the go version to latest if you're not worried about breaking when the Go compiler updates.

Finally, an even simpler way to build Go images is with the [ko](https://github.com/ko-build/ko) project, which avoids the need to use `docker build` entirely.

**Comment by justaugustus** [comment]
Thanks for catching this, Chainguardians!
Merged @amouat's multi-stage builds PR and opened a follow-up for `ko`: https://github.com/uwu-tools/gh-jira-issue-sync/issues/155
