### ISSUE TITLE
Comment regular expression is fragile

### ISSUE THREAD

**Issue by justaugustus** [uwu-tools/gh-jira-issue-sync#9]
From: https://github.com/coreos/issue-sync/issues/29

> In some comments in our repository the comments regexp in `comments.go` fails to match at all, and sync fails since fields is empty.
> 
> As a ugly quickfix I had to add
> 
> ```
> if len(fields) != 5 {
> 		log.Debug("Failed to update JIRA comment for ", jIssue.ID)
> 		return nil
> 	}
> ```
> 
> To `UpdateComment` to make sync work. Also writing the config to home failed on macOS, but worked when I specified a full file path. I can add a separate issue about that if needed.

**Comment by rappizs** [comment]
I believe we need more explanation about this bug to be able to start working on it.
